project:
  type: website

website:
  title: "Matthew Swanson"
  site-url: https://matthew-swanson.com
  description: "This is Matthew Swanson's personal portfolio and blog."
  reader-mode: true
  navbar:
    logo: "/images/Logo.gif"
    search: true
    pinned: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Portfolio"
        href: PortMain.qmd
      - text: "Publications"
        href: Publications.qmd
      - text: "Data Viz Portfolio"
        href: DataViz.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/matthew-swanson-phd-335942137
      - icon: envelope
        href: "mailto:mattswnsn53@gmail.com"
      - text: CV
        icon: file-text
        href: Matthew Austin Swanson CV 2025.pdf
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/MattS002/Quarto-Portfolio
          - text: Report an issue
            href: https://github.com/MattS002/Quarto-Portfolio/issues
  page-footer:
    background: dark
    left: " © 2025, Matthew Swanson. This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)." 
    right: 
      - text: Made with Quarto
        href: https://quarto.org
      - icon: github
        href: https://github.com/MattS002
      - icon: linkedin 
        href: https://www.linkedin.com/in/matthew-swanson-phd-335942137

format:
  html:
    theme:
      dark: Superhero
    css: styles.css
    toc: true

editor: visual

