{
  "hash": "5a7c960d678298a4ef45adbfc90c56f9",
  "result": {
    "markdown": "---\ntitle: \"Factorial Anova and Power Analysis in R\"\neditor: visual\nauthor: Matthew Swanson\ncategories: ['Factorial ANOVA', 'R', 'Power Analysis', 'Effect Size', 'Clinical Trial Data']\nwarning: FALSE\nmessage: FALSE\n---\n\n\n::: text-center\n# **Project Goal**\n:::\n\nIt is of interest to a client to analyze data from a clinical trial on tooth growth. It is of particular interest to ascertain how different dosage amounts and types of supplements influence tooth growth. First, I will need to load the data set and calculate data descriptives and run some ANOVAs.\n\nLoading the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"ToothGrowth\")\nhead(ToothGrowth)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   len supp dose\n1  4.2   VC  0.5\n2 11.5   VC  0.5\n3  7.3   VC  0.5\n4  5.8   VC  0.5\n5  6.4   VC  0.5\n6 10.0   VC  0.5\n```\n:::\n:::\n\n\nNeed cell means and variances next.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nToothGrowth %>%\ngroup_by(supp, dose)%>%\nsummarize(group_mean = mean(len), n = n(), var = var(len)) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n# Groups:   supp [2]\n  supp   dose group_mean     n   var\n  <fct> <dbl>      <dbl> <int> <dbl>\n1 OJ      0.5      13.2     10 19.9 \n2 OJ      1        22.7     10 15.3 \n3 OJ      2        26.1     10  7.05\n4 VC      0.5       7.98    10  7.54\n5 VC      1        16.8     10  6.33\n6 VC      2        26.1     10 23.0 \n```\n:::\n:::\n\n\n::: text-center\n# **Factorial ANOVA**\n:::\n\nGlancing at these cell means indicates a potential pattern. Namely, that across supplement, as dosage increases, tooth length increases. It also appears that across dosage, the OJ supplement produces longer teeth growth than the VC supplement. However, to determine if these mean differences are significant, I need to conduct a factorial ANOVA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Need to ensure that R reads factor variables as factors first\n\nToothGrowth$supp <- as.factor(ToothGrowth$supp)\nToothGrowth$dose <- as.factor(ToothGrowth$dose)\nFactorANOVA <- aov(len ~ dose*supp, ToothGrowth) #you can also just add in dose*supp and R understands to include the interaction and both main effects in the model - nice way to shorten code\n\nsummary(FactorANOVA)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \ndose         2 2426.4  1213.2  92.000  < 2e-16 ***\nsupp         1  205.4   205.4  15.572 0.000231 ***\ndose:supp    2  108.3    54.2   4.107 0.021860 *  \nResiduals   54  712.1    13.2                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\n#Calculating Marginal Means\n\nlibrary(emmeans)\n\nCondition_Means <- emmeans(FactorANOVA, ~ supp*dose)\nCondition_Means\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n supp dose emmean   SE df lower.CL upper.CL\n OJ   0.5   13.23 1.15 54    10.93     15.5\n VC   0.5    7.98 1.15 54     5.68     10.3\n OJ   1     22.70 1.15 54    20.40     25.0\n VC   1     16.77 1.15 54    14.47     19.1\n OJ   2     26.06 1.15 54    23.76     28.4\n VC   2     26.14 1.15 54    23.84     28.4\n\nConfidence level used: 0.95 \n```\n:::\n\n```{.r .cell-code}\nMarginal_MeansSupp <- emmeans(FactorANOVA, ~ supp)\nMarginal_MeansSupp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n supp emmean    SE df lower.CL upper.CL\n OJ     20.7 0.663 54     19.3     22.0\n VC     17.0 0.663 54     15.6     18.3\n\nResults are averaged over the levels of: dose \nConfidence level used: 0.95 \n```\n:::\n\n```{.r .cell-code}\nMarginal_MeansDose <- emmeans(FactorANOVA, ~ dose)\nMarginal_MeansDose\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n dose emmean    SE df lower.CL upper.CL\n 0.5    10.6 0.812 54     8.98     12.2\n 1      19.7 0.812 54    18.11     21.4\n 2      26.1 0.812 54    24.47     27.7\n\nResults are averaged over the levels of: supp \nConfidence level used: 0.95 \n```\n:::\n:::\n\n\nA quick glance at the output highlights that both the main effects of dose and supplement are significant as well as their interaction. Across supplement type, the means of tooth length were significantly different among three dosage conditions: 0.5 dosage (M = 10.61), 1.0 dosage (M = 19.74), and 2.0 dosage (M = 26.10), F(2,54) = 92.00, p \\<.001. There was also a statistically significant difference in the average tooth length between supplement type, across dosage: OJ (M = 20.66) and VC condition (M = 16.96), F(1,54) = 15.57, p \\<.001. The interaction between dosage amount and supplement type was significant, F(2,54) = 4.11, p =.02.\n\n::: text-center\n## **Simple Effects**\n:::\n\nGiven the significant interaction, I know that the effects of one variable depends on the levels of the other variable. One way to understand this effect is to look at the simple effects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(phia)\n\nlm1 <- lm(len ~ dose*supp, ToothGrowth)\n\nTest1 <- testInteractions(lm1, fixed = \"dose\", across = \"supp\")\nTest1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nF Test: \nP-value adjustment method: holm\n          Value Df Sum of Sq       F   Pr(>F)   \n0.5        5.25  1    137.81 10.4505 0.004185 **\n  1        5.93  1    175.82 13.3330 0.001769 **\n  2       -0.08  1      0.03  0.0024 0.960893   \nResiduals       54    712.11                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nTest2 <- testInteractions(lm1, fixed = \"supp\", across = \"dose\")\nTest2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nF Test: \nP-value adjustment method: holm\n           dose1 dose2 Df Sum of Sq      F    Pr(>F)    \nOJ        -12.83 -3.36  2    885.26 33.565 3.363e-10 ***\nVC        -18.16 -9.37  2   1649.49 62.541 1.751e-14 ***\nResiduals              54    712.11                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\ncontrast(Condition_Means, \"revpairwise\", by= \"dose\", adjust = \"none\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndose = 0.5:\n contrast estimate   SE df t.ratio p.value\n VC - OJ     -5.25 1.62 54  -3.233  0.0021\n\ndose = 1:\n contrast estimate   SE df t.ratio p.value\n VC - OJ     -5.93 1.62 54  -3.651  0.0006\n\ndose = 2:\n contrast estimate   SE df t.ratio p.value\n VC - OJ      0.08 1.62 54   0.049  0.9609\n```\n:::\n:::\n\n\nNote here the significance levels: for example, the effects of supplement within 0.5 & 1.0 dosage levels are significant. Additionally, the effects of dosage within OJ and VC supplement are also significant. Looking at the contrast estimates, it becomes clear that For both dosage levels of 0.5 and 1.0, teeth grow significantly less when the patient is also provided a vitamin C supplement, compared to the teeth of patients provided an orange juice supplement, t(54) = -3.23, p =.002 and t(54) = -3.65, p \\<.001 respectively.\n\n::: text-center\n## **Effect Sizes**\n:::\n\nNow let's collect both biased and unbiased estimates of effect size for our three effects in this model. This will help clarify the magnitude of effect of both dosage and supplement type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lsr)\nlibrary(effectsize)\n\nEta <- etaSquared(FactorANOVA, type = 2, anova = TRUE)\nEta\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              eta.sq eta.sq.part       SS df         MS         F            p\ndose      0.70286419   0.7731092 2426.434  2 1213.21717 91.999965 0.0000000000\nsupp      0.05948365   0.2238254  205.350  1  205.35000 15.571979 0.0002311828\ndose:supp 0.03137672   0.1320279  108.319  2   54.15950  4.106991 0.0218602690\nResiduals 0.20627544          NA  712.106 54   13.18715        NA           NA\n```\n:::\n\n```{.r .cell-code}\nomega_squared(FactorANOVA, partial = FALSE, ci = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# Effect Size for ANOVA (Type I)\n\nParameter | Omega2 |       95% CI\n---------------------------------\ndose      |   0.69 | [0.57, 1.00]\nsupp      |   0.06 | [0.00, 1.00]\ndose:supp |   0.02 | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n:::\n\n```{.r .cell-code}\nomega_squared(FactorANOVA, partial = TRUE, ci = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# Effect Size for ANOVA (Type I)\n\nParameter | Omega2 (partial) |       95% CI\n-------------------------------------------\ndose      |             0.75 | [0.65, 1.00]\nsupp      |             0.20 | [0.06, 1.00]\ndose:supp |             0.09 | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n:::\n:::\n\n\nThe eta squared value associated with the interaction between dosage and supplement is .03. In other words, the interaction term explains approximately 3% of the variance in tooth length. Its' respective partial eta squared value is .13, indicating that the interaction term explains about 13% of the unique variance in tooth length, accounting for any shared variance with dosage and supplement. The interaction term's omega squared and partial omega squared values are slightly smaller as these effect sizes have been corrected for bias but the interpretation stays the same.\n\n::: text-center\n# **Power Analysis**\n:::\n\nNow, I will calculate power for this analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pwr)\n\nf <- sqrt(0.031376 / (1-0.031376))\npwr.anova.test(k = 6, n = 10, f = f, sig.level = .95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     Balanced one-way analysis of variance power calculation \n\n              k = 6\n              n = 10\n              f = 0.1799787\n      sig.level = 0.95\n          power = 0.9778168\n\nNOTE: n is number in each group\n```\n:::\n:::\n\n\nI have about a 98% power level to detect the interaction effect in our data, should the effect truly exist. What about the main effect of supplement?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf <- sqrt(0.05948365 / (1-0.05948365))\npwr.anova.test(k = 2, n = 30, f = f, sig.level = .95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     Balanced one-way analysis of variance power calculation \n\n              k = 2\n              n = 30\n              f = 0.2514871\n      sig.level = 0.95\n          power = 0.9924828\n\nNOTE: n is number in each group\n```\n:::\n:::\n\n\nI have a 99% power level to detect the effect of supplement, should the effect exist.\n\n::: text-center\n# **Visualizations**\n:::\n\nThe client also requested some visualizations, so I will create a bar and line graph of the above group means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(ToothGrowth, aes(x =as.factor(dose), y = len, fill = as.factor(supp))) + \n  stat_summary(fun='mean',geom='bar', position = \"dodge\") +\n  labs(x = \"Dosage\", y = \"Tooth Length\", fill = \"Supplement Type\", title = \"Figure 1\", subtitle = \"Mean Tooth Length Scores by Dosage and Supplement\")+\n  theme(plot.title = element_text(face = \"bold\"),\n        plot.subtitle = element_text(face = \"italic\")) +\n  scale_fill_manual(values = c(\"#D71920\", \"#002266\"))\n```\n\n::: {.cell-output-display}\n![](FactorPower_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\ninteraction.plot(x.factor = ToothGrowth$dose, #x-axis variable\n                 trace.factor = ToothGrowth$supp, #variable for lines\n                 response = ToothGrowth$len, #y-axis variable\n                 fun = mean, #metric to plot\n                 ylab = \"Tooth Length\",\n                 xlab = \"Dosage\",\n                 col = c(\"pink\", \"blue\"),\n                 lty = 1, #line type\n                 lwd = 2, #line width\n                 trace.label = \"Supplement Type\")\n```\n\n::: {.cell-output-display}\n![](FactorPower_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n:::\n",
    "supporting": [
      "FactorPower_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}