{
  "hash": "8ed2f4fe9d7cc1119e716a38e40cf642",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Does Birth Order Impact SAT Scores?\"\neditor: visual\nauthor: Matthew Swanson\ncategories: ['Repeated Measures ANOVA', 'R', 'emmeans', 'Data Conversion']\nwarning: FALSE\nmessage: FALSE\n---\n\n\n\n![](/images/computers.jpeg)\n\n::: text-center\n# **Project Goal**\n:::\n\nThe overarching goal of this project is to teach readers how to run a repeated measures ANOVA in R. I will walk through the code below but readers should be familiar with R code prior to working through this code.\n\nThis data contains SAT scores for six families, with each family consisting of an older, middle, and younger child. Higher values indicate better SAT scores. I am interested in assessing if birth order in a family with three children effects the child's SAT score.\n\nFirst I will need to read in the data and a few packages. I only do a bit of cleaning at this stage (i.e., reformatting the dataframe) so prior data cleaning should have already been completed.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(dplyr)\nlibrary(ez)\nlibrary(tidyr)\nlibrary(tidyverse)\n\nhead(Data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  family young middle oldest\n   <dbl> <dbl>  <dbl>  <dbl>\n1      1    54     55     65\n2      2    48     63     59\n3      3    57     54     67\n4      4    61     61     62\n5      5    63     60     61\n6      6    52     54     55\n```\n\n\n:::\n:::\n\n\n\n::: text-center\n# **Converting Data Format**\n:::\n\nIf you look at the data file, you will notice that participants are listed column wise and not row wise since the same family has multiple evaluation points (i.e., three children in a family). I need to flip this so that the data is in long form.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Need to convert data set to long format - it is currently in wide format\n\nDataLong <- Data %>%\ngather(key = \"order\", value = \"score\", young, middle, oldest) \n#I called these new variables order and score (you can name them what you like so long as it makes sense). \n\n#Here you want to gather by the grouping factor and make sure the values by group are contained in a new variable, row-wise\n\nDataLong$family <- as.factor(DataLong$family)\nDataLong$order <- as.factor(DataLong$order)\nDataLong\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 3\n   family order score\n   <fct>  <fct> <dbl>\n 1 1      young    54\n 2 2      young    48\n 3 3      young    57\n 4 4      young    61\n 5 5      young    63\n 6 6      young    52\n 7 7      young    43\n 8 8      young    69\n 9 9      young    50\n10 10     young    58\n# ℹ 20 more rows\n```\n\n\n:::\n:::\n\n\n\nCheck how the long version of this data set and the original data set compare. This should help signal how I converted the data to long form and why I had to do so. Next, I want to check that the design is balanced. Unbalanced designs typically violate important assumptions of equal variance (among other issues) so great caution should be taken when conducting unbalanced repeated measures ANOVA.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDataLong %>%\ngroup_by(order) %>%\nsummarise(n = n(), sd = sd(score), var = var(score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  order      n    sd   var\n  <fct>  <int> <dbl> <dbl>\n1 middle    10  6.09  37.1\n2 oldest    10  8.63  74.4\n3 young     10  7.71  59.4\n```\n\n\n:::\n:::\n\n\n\n::: text-center\n# **Repeated Measures ANOVA**\n:::\n\nEach cell has the same n size so this design is balanced. Now I am going to run this repeated measures ANOVA three different ways to get different information and so that subsequent functions have the correct object to run. Let's assess if birth order in a family with three children effects the child's SAT score.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRepeated <- ezANOVA(DataLong, dv = score, wid = family, within = order, detailed = TRUE, return_aov = TRUE)\n\nRepeated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$ANOVA\n       Effect DFn DFd         SSn       SSd          F            p p<.05\n1 (Intercept)   1   9 98957.63333 1267.3667 702.731675 7.476640e-10     *\n2       order   2  18    95.26667  270.7333   3.166954 6.630493e-02      \n         ges\n1 0.98469487\n2 0.05832534\n\n$`Mauchly's Test for Sphericity`\n  Effect       W         p p<.05\n2  order 0.96018 0.8499836      \n\n$`Sphericity Corrections`\n  Effect       GGe      p[GG] p[GG]<.05      HFe      p[HF] p[HF]<.05\n2  order 0.9617049 0.06888936           1.217684 0.06630493          \n\n$aov\n\nCall:\naov(formula = formula(aov_formula), data = data)\n\nGrand Mean: 57.43333\n\nStratum 1: family\n\nTerms:\n                Residuals\nSum of Squares   1267.367\nDeg. of Freedom         9\n\nResidual standard error: 11.8667\n\nStratum 2: family:order\n\nTerms:\n                    order Residuals\nSum of Squares   95.26667 270.73333\nDeg. of Freedom         2        18\n\nResidual standard error: 3.878239\nEstimated effects may be unbalanced\n```\n\n\n:::\n\n```{.r .cell-code}\nModel <- aov(score ~ order + Error(family/order), DataLong) \n#Because order is crossed with the random factor family (i.e., each order exists in a particular family), you must specify the error term for order, which in this case is family by order. Do this by adding the term Error(family/order) to the factor order, as shown above.\n\nsummary(Model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nError: family\n          Df Sum Sq Mean Sq F value Pr(>F)\nResiduals  9   1267   140.8               \n\nError: family:order\n          Df Sum Sq Mean Sq F value Pr(>F)  \norder      2  95.27   47.63   3.167 0.0663 .\nResiduals 18 270.73   15.04                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(rstatix)\nSphereCorr <- anova_test(DataLong, dv = score, wid = family, within = order)\nSphereCorr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nANOVA Table (type III tests)\n\n$ANOVA\n  Effect DFn DFd     F     p p<.05   ges\n1  order   2  18 3.167 0.066       0.058\n\n$`Mauchly's Test for Sphericity`\n  Effect    W    p p<.05\n1  order 0.96 0.85      \n\n$`Sphericity Corrections`\n  Effect   GGe      DF[GG] p[GG] p[GG]<.05   HFe      DF[HF] p[HF] p[HF]<.05\n1  order 0.962 1.92, 17.31 0.069           1.218 2.44, 21.92 0.066          \n```\n\n\n:::\n:::\n\n\n\nResults indicate that there is no order effect here on SAT scores, F(2, 18) = 3.17, p = .066 (effect is marginal so we will interpret it for the sake of this example).\n\nSome notes on the output: GES refers to the generalized eta square value. W refers to the Machly's W statistic, a non-significant p value indicates that sphericity assumption is met. GGe is the greenhouse-geisser epsilon value and HFe is the Huynh-Feldt epsilon value (use these tests if the spherictiy assumption isn't met). If you want the correct df for either epsilon value, look at the output from the \"anova_test\" function.\n\nNote that sphericity output is only provided when you have at least 3 factors for an IV (the results are the same for 2 levels of a factor so no output is provided).\n\n::: text-center\n## **Post Hoc Tests**\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Post Hoc Testing\nlibrary(emmeans)\n\nCell_Means <- emmeans(Model, ~ order)\nCell_Means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n order  emmean   SE df lower.CL upper.CL\n middle   57.0 2.39 13     51.8     62.2\n oldest   59.8 2.39 13     54.6     65.0\n young    55.5 2.39 13     50.3     60.7\n\nWarning: EMMs are biased unless design is perfectly balanced \nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\npwc <- DataLong %>%\npairwise_t_test(score ~ order, paired = TRUE,p.adjust.method = \"bonferroni\")\n\npwc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 10\n  .y.   group1 group2    n1    n2 statistic    df     p p.adj p.adj.signif\n* <chr> <chr>  <chr>  <int> <int>     <dbl> <dbl> <dbl> <dbl> <chr>       \n1 score middle oldest    10    10    -1.51      9 0.164 0.492 ns          \n2 score middle young     10    10     0.841     9 0.422 1     ns          \n3 score oldest young     10    10     2.76      9 0.022 0.066 ns          \n```\n\n\n:::\n:::\n\n\n\n::: text-center\n# **Solution**\n:::\n\nUsing the pairwise t test code above, I can compare levels of the factor to each other just like in previous weeks. For example, t-test results indicate that the oldest siblings had marginally larger SAT scores (M = 59.8) than the youngest siblings (M = 55.5) within each family t(9) = 2.76, p = .07. Again, none of these results meet traditional p-value cutoff scores, so we would conclude that SAT scores did not depend on birth order.\n\nIn this data, children were ordered by birth and grouped within family and SAT values were compared between children. However, all data were collected at one time point. How might this data be analyzed if each child had multiple SAT scores? I cover how to conduct a between and within repeated measures ANOVA in another project already posted in my portfolio tab so feel free to check it out if you are curious!\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}