{
  "hash": "9e8535d7435767f68a3cca7f9175f83d",
  "result": {
    "markdown": "---\ntitle: \"Employee Turnover: A Survival Analysis\"\neditor: visual\nauthor: Matthew Swanson\ncategories: ['Survival Analysis', 'Turnover', 'R', 'Visualizations', 'survminer']\nwarning: FALSE\nmessage: FALSE\n---\n\n\n::: text-center\n# **Project Goal**\n:::\n\nEmployees choose to leave organizations for many [reasons](https://journals.aom.org/doi/abs/10.5465/amp.2016.0123). Thus, it is sometimes important for Human Resources and People Analytic departments to identify variables that may influence the likelihood that employees will turnover.\n\n::: text-center\n## **About This Data**\n:::\n\nUsing [this](https://www.kaggle.com/datasets/davinwijaya/employee-turnover) real employee dataset shared by Edward Babushkin and housed on Kaggle, I will analyze several factors that influence the likelihood that an employee will leave their company. Also, a big thank you to Keith McNulty, Alex LoPilato, and Liz Romero for their people analytics course on [github](https://github.com/rstudio-conf-2022/people-analytics-rstats).\n\nData columns:\n\n-   stag = job tenure (time in months)\n\n-   event = employee turnover event\n\n-   gender = employee's gender\n\n-   age = employee's age\n\n-   industry = employee's industry\n\n-   profession = employee's profession\n\n-   traffic = from what pipeline an employee came to the company\n\n-   coach = presence of training coach\n\n-   head_gender = supervisor gender\n\n-   greywage = wage type (taxed or not)\n\n-   way = employee's mode of transportation\n\n-   extraversion = extraversion score\n\n-   independ = agreeableness score\n\n-   selfcontrol = conscientiousness score\n\n-   anxiety = neuroticism score\n\n-   novator = openness score\n\nFirst, I will load in the data and make any necessary corrections.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(dplyr)\nlibrary(tidyverse)\nlibrary(psych)\n\n\n#Need to change string data to factors\nTurnData$event <- factor(TurnData$event, labels = c(\"no\", \"yes\"))\nnames <- c('gender', 'industry', 'profession', 'traffic', 'coach', 'head_gender', 'greywage', 'way')\nTurnData[,names] <- lapply(TurnData[,names], factor)\nTurnData <- TurnData  %>%\n    dplyr::mutate(\n    Coach = dplyr::case_when(\n      coach == \"no\" ~ \"no\",\n      coach == \"yes\" ~ \"yes\",\n      coach == \"my head\" ~ \"no\"))\nTurnData$Coach <- as.factor(TurnData$Coach)\nstr(TurnData)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t1129 obs. of  17 variables:\n $ stag        : num  7.03 22.97 15.93 15.93 8.41 ...\n $ event       : Factor w/ 2 levels \"no\",\"yes\": 2 2 2 2 2 2 2 2 2 2 ...\n $ gender      : Factor w/ 2 levels \"f\",\"m\": 2 2 1 1 2 1 1 1 1 1 ...\n $ age         : num  35 33 35 35 32 42 42 28 29 30 ...\n $ industry    : Factor w/ 16 levels \" HoReCa\",\"Agriculture\",..: 3 3 11 11 13 8 8 13 3 5 ...\n $ profession  : Factor w/ 15 levels \"Finan\\xf1e\",\"Accounting\",..: 8 8 8 8 4 8 8 8 8 12 ...\n $ traffic     : Factor w/ 8 levels \"advert\",\"empjs\",..: 5 2 5 5 8 2 2 7 2 8 ...\n $ coach       : Factor w/ 3 levels \"my head\",\"no\",..: 2 2 2 2 3 3 3 2 2 3 ...\n $ head_gender : Factor w/ 2 levels \"f\",\"m\": 1 2 2 2 1 2 2 2 1 2 ...\n $ greywage    : Factor w/ 2 levels \"grey\",\"white\": 2 2 2 2 2 2 2 2 2 2 ...\n $ way         : Factor w/ 3 levels \"bus\",\"car\",\"foot\": 1 1 1 1 1 1 1 1 1 1 ...\n $ extraversion: num  6.2 6.2 6.2 5.4 3 6.2 6.2 3.8 8.6 5.4 ...\n $ independ    : num  4.1 4.1 6.2 7.6 4.1 6.2 6.2 5.5 6.9 5.5 ...\n $ selfcontrol : num  5.7 5.7 2.6 4.9 8 4.1 4.1 8 2.6 3.3 ...\n $ anxiety     : num  7.1 7.1 4.8 2.5 7.1 5.6 5.6 4 4 7.9 ...\n $ novator     : num  8.3 8.3 8.3 6.7 3.7 6.7 6.7 4.4 7.5 8.3 ...\n $ Coach       : Factor w/ 2 levels \"no\",\"yes\": 1 1 1 1 2 2 2 1 1 2 ...\n```\n:::\n:::\n\n\nFactors have been made - now I will look at the descriptives of the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nDescriptives <- describe(TurnData)\nDescriptives\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             vars    n  mean    sd median trimmed   mad   min    max  range\nstag            1 1129 36.63 34.10  24.34   31.05 24.50  0.39 179.45 179.06\nevent*          2 1129  1.51  0.50   2.00    1.51  0.00  1.00   2.00   1.00\ngender*         3 1129  1.24  0.43   1.00    1.18  0.00  1.00   2.00   1.00\nage             4 1129 31.07  7.00  30.00   30.54  7.41 18.00  58.00  40.00\nindustry*       5 1129  9.00  4.07   8.00    9.04  5.93  1.00  16.00  15.00\nprofession*     6 1129  8.21  2.39   8.00    8.13  0.00  1.00  15.00  14.00\ntraffic*        7 1129  5.00  2.42   5.00    5.04  4.45  1.00   8.00   7.00\ncoach*          8 1129  1.84  0.61   2.00    1.80  0.00  1.00   3.00   2.00\nhead_gender*    9 1129  1.52  0.50   2.00    1.52  0.00  1.00   2.00   1.00\ngreywage*      10 1129  1.89  0.32   2.00    1.98  0.00  1.00   2.00   1.00\nway*           11 1129  1.50  0.68   1.00    1.38  0.00  1.00   3.00   2.00\nextraversion   12 1129  5.59  1.85   5.40    5.58  2.37  1.00  10.00   9.00\nindepend       13 1129  5.48  1.70   5.50    5.48  2.08  1.00  10.00   9.00\nselfcontrol    14 1129  5.60  1.98   5.70    5.59  2.22  1.00  10.00   9.00\nanxiety        15 1129  5.67  1.71   5.60    5.63  2.22  1.70  10.00   8.30\nnovator        16 1129  5.88  1.90   6.00    5.94  2.22  1.00  10.00   9.00\nCoach*         17 1129  1.12  0.32   1.00    1.02  0.00  1.00   2.00   1.00\n              skew kurtosis   se\nstag          1.49     2.02 1.01\nevent*       -0.02    -2.00 0.01\ngender*       1.19    -0.59 0.01\nage           0.66     0.06 0.21\nindustry*    -0.03    -1.28 0.12\nprofession*   0.26     2.52 0.07\ntraffic*     -0.03    -1.50 0.07\ncoach*        0.10    -0.43 0.02\nhead_gender* -0.07    -2.00 0.01\ngreywage*    -2.45     4.00 0.01\nway*          1.00    -0.23 0.02\nextraversion  0.01    -0.40 0.06\nindepend     -0.01    -0.34 0.05\nselfcontrol   0.03    -0.63 0.06\nanxiety       0.15    -0.48 0.05\nnovator      -0.25    -0.48 0.06\nCoach*        2.38     3.67 0.01\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(TurnData))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nSince each data point represents an employee who has either left the organization or is currently employed, and there are no missing data points, I will move on to model building and running some analyses on the data.\n\n::: text-center\n# **Survival Analysis**\n:::\n\nFirst, I conducted a survival analysis and related the survival object to several of the variables that were measured during the employee on-boarding period.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survival)\nlibrary(survminer)\nlibrary(lubridate)\nlibrary(ggfortify)\n# Create a censor indicator variable that is 1 if the employee has left and 0 otherwise\nTurnData <-\n  TurnData %>%\n    dplyr::mutate(\n    CENSOR = dplyr::case_when(\n      event == \"no\" ~ 0,\n      TRUE ~ 1))\n\n# Create a survival object\nsurv_object <- survival::Surv(\n  event = TurnData$CENSOR,\n  time = TurnData$stag\n)\n\n# Estimate survival probabilities using Kaplan Meier estimator\nSurvProb <- survival::survfit(\n  surv_object ~ 1,\n  data = TurnData)\nhead(fortify(SurvProb),10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        time n.risk n.event n.censor      surv      std.err     upper     lower\n1  0.3942505   1129       1        0 0.9991143 0.0008861321 1.0000000 0.9973805\n2  0.4271047   1128       1        0 0.9982285 0.0012537359 1.0000000 0.9957786\n3  0.4928131   1127       0        3 0.9982285 0.0012537359 1.0000000 0.9957786\n4  0.5256674   1124       0        1 0.9982285 0.0012537359 1.0000000 0.9957786\n5  0.6899384   1123       0        1 0.9982285 0.0012537359 1.0000000 0.9957786\n6  0.7556468   1122       1        0 0.9973388 0.0015384787 1.0000000 0.9943360\n7  0.7885010   1121       0        1 0.9973388 0.0015384787 1.0000000 0.9943360\n8  0.8870637   1120       0        1 0.9973388 0.0015384787 1.0000000 0.9943360\n9  0.9199179   1119       1        0 0.9964476 0.0017793961 0.9999288 0.9929784\n10 1.1170431   1118       2        0 0.9946650 0.0021838533 0.9989316 0.9904167\n```\n:::\n\n```{.r .cell-code}\nSurvProbcalc <- \n  tibble::tibble(\n    time = SurvProb$time,\n    n.risk = SurvProb$n.risk,\n    n.censor = SurvProb$n.censor,\n    n.event = SurvProb$n.event,\n    survival = SurvProb$surv\n  )\n\nsum(SurvProbcalc$n.event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 571\n```\n:::\n\n```{.r .cell-code}\nsum(SurvProbcalc$n.censor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 558\n```\n:::\n\n```{.r .cell-code}\nmin(which(SurvProbcalc$n.censor != 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3\n```\n:::\n:::\n\n\nFYI: To reduce the length of the printed data, I only asked for the first 10 rows but a row is created until the \"surv\" column reaches zero so this output can become quite long.\n\nThe first item I notice from this output is that turnover occurs at a relatively rapid rate at this company (this interpretation may slightly change if the organization is a massive company - total N size is not accessable). Since the time metric is in months, by the first year, approximately 297 employees (1129 - 832) are predicted to turnover, for a survival percentage of about 85%. Additionally, I would expect only half of the employees to remain at the company about 4 years into the job (approximately 50 months).\n\nI also determined that 571 employees turned over at this company and there are 558 censored observations. These censored observations are participants who have not yet experienced the event of interest in this dataset: turnover. Also, the first censored participant showed up at time point three (about 2 weeks).\n\nNow I will visualize the Kaplan Meier estimator output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvminer::ggsurvplot(\n  SurvProb,\n  pval = TRUE,\n  conf.int = TRUE,\n  risk.table = TRUE,\n  xlab = \"Months since Hire\",\n  ylab = \"Probability of Staying at Company\"\n)\n```\n\n::: {.cell-output-display}\n![](Turnover_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nConsidering no other explanatory variables, results of my survival analysis predicts that most employees will turnover about 175 months (14.5 years) into their tenure at the company. However, perhaps additional variables, such a the presence of a coach and commuting style better explain the tenure trajectory of employees at this company.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSurvProb_Coach <- survival::survfit(surv_object ~ Coach, data = TurnData)\nhead(fortify(SurvProb_Coach), 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        time n.risk n.event n.censor      surv     std.err     upper     lower\n1  0.3942505    997       1        0 0.9989970 0.001003512 1.0000000 0.9970340\n2  0.4928131    996       0        3 0.9989970 0.001003512 1.0000000 0.9970340\n3  0.5256674    993       0        1 0.9989970 0.001003512 1.0000000 0.9970340\n4  0.6899384    992       0        1 0.9989970 0.001003512 1.0000000 0.9970340\n5  0.7556468    991       1        0 0.9979889 0.001423486 1.0000000 0.9952084\n6  0.7885010    990       0        1 0.9979889 0.001423486 1.0000000 0.9952084\n7  0.8870637    989       0        1 0.9979889 0.001423486 1.0000000 0.9952084\n8  1.1170431    988       2        0 0.9959687 0.002019739 0.9999192 0.9920338\n9  1.1498973    986       0        1 0.9959687 0.002019739 0.9999192 0.9920338\n10 1.1827515    985       0        2 0.9959687 0.002019739 0.9999192 0.9920338\n   strata\n1      no\n2      no\n3      no\n4      no\n5      no\n6      no\n7      no\n8      no\n9      no\n10     no\n```\n:::\n:::\n\n\nAt a quick glance, it appears that the presence of a coach speeds up the attrition rate at this company! Perhaps the company should investigate the coaches they have employed to work with their staff as employees have a lower survival rate when paired with a coach than those who do not have a coach. [**However**]{.underline}, I want a statistical test to tell the difference between these two survival curves. I will now visualize these survival rates and ask for a test of the difference in survival curves.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvminer::ggsurvplot(\n  SurvProb_Coach,\n  pval = TRUE,\n  conf.int = TRUE,\n  xlab = \"Months since Hire\",\n  ylab = \"Probability of Staying at Company\"\n)\n```\n\n::: {.cell-output-display}\n![](Turnover_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nAs is made more clear by this graph, the survival curves for those who had and did not have a coach did not significantly differ from each other, log-likelihood p = .27. I am also curious how commuting style (if the employee commuted by way of a bus, car, or by foot) impacted attrition and if commuting style interacted with coaching. First, I will change my model to include commuting style and will plot the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSurvProb_Way <- survival::survfit(surv_object ~ way, data = TurnData)\n#summary(SurvProb_Sup)\nsurvminer::ggsurvplot(\n  SurvProb_Way,\n  pval = TRUE,\n  conf.int = TRUE,\n  xlab = \"Months since Hire\",\n  ylab = \"Probability of Staying at Company\"\n)\n```\n\n::: {.cell-output-display}\n![](Turnover_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nResults indicate that commuting style did significantly change the attrition estimate for employees. Since there are more than two curves, this only tells me that at least one of the curves differs from the others, but not which curves those are. I will come back to this issue in a moment.\n\nNow I want to see how the occurrence of coaching potentially interacts with commuting style in predicting attrition rates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nIntModel <- survival::survfit(surv_object ~ Coach + way, data = TurnData)\nsurvminer::ggsurvplot(IntModel, \n  pval = TRUE,\n  xlab = \"Months since Hire\",\n  ylab = \"Probability of Staying at Company\")\n```\n\n::: {.cell-output-display}\n![](Turnover_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nNote here the significant log-likelihood p value. I also removed the shading for confidence intervals to aid in readability. To really understand the group differences in survivability, the Cox-Proportional Hazards Model, a semi-parametric regression model, will be utilized. I also decided to add in participant's conscientiousness scores to the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCoxMod <- survival::coxph(\n  surv_object ~  Coach + way + selfcontrol + Coach*way,\n  data = TurnData)\nsummary(CoxMod)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\nsurvival::coxph(formula = surv_object ~ Coach + way + selfcontrol + \n    Coach * way, data = TurnData)\n\n  n= 1129, number of events= 571 \n\n                     coef exp(coef) se(coef)      z Pr(>|z|)   \nCoachyes          0.20012   1.22155  0.15303  1.308  0.19097   \nwaycar           -0.22041   0.80219  0.09940 -2.217  0.02659 * \nwayfoot          -0.42755   0.65210  0.17874 -2.392  0.01675 * \nselfcontrol      -0.05915   0.94257  0.02118 -2.793  0.00522 **\nCoachyes:waycar  -0.19537   0.82253  0.29951 -0.652  0.51421   \nCoachyes:wayfoot -0.24507   0.78265  0.42224 -0.580  0.56165   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n                 exp(coef) exp(-coef) lower .95 upper .95\nCoachyes            1.2215     0.8186    0.9050    1.6488\nwaycar              0.8022     1.2466    0.6602    0.9747\nwayfoot             0.6521     1.5335    0.4594    0.9257\nselfcontrol         0.9426     1.0609    0.9042    0.9825\nCoachyes:waycar     0.8225     1.2158    0.4573    1.4794\nCoachyes:wayfoot    0.7827     1.2777    0.3421    1.7905\n\nConcordance= 0.552  (se = 0.013 )\nLikelihood ratio test= 21.52  on 6 df,   p=0.001\nWald test            = 21.13  on 6 df,   p=0.002\nScore (logrank) test = 21.29  on 6 df,   p=0.002\n```\n:::\n:::\n\n\n::: text-center\n# **Conclusion**\n:::\n\nResults indicate that coaching style did not significantly interact with commuting type, all *ps*\\>.05, nor was there any group difference for participants who had a coach vs. those who did not, *b* = 0.20, *p* = .19. However, the difference between riding the bus to work and commuting by either car, *b* = -0.22, *p* = .03, or by foot, *b* = -0.43, *p* = .02, were significant and negative. This suggests that when compared to riding the bus, driving to work reduces the hazard (of attrition) by a factor of .80 and walking to work reduces the hazard by .65. Self-control was also a significant predictor, such that every unit increase in conscientiousness reduces the hazard by a factor of .94.\n\nIt is my recommendation that the company evaluates the utility of their coaching program, as employees are no less likely to leave the company when they have a coach, compared to those who do not have coaches. Conscientious and commuting style stand out as significant predictors of the survival curves. Thus, it may be advantageous to the company to consider adding conscientiousness personality tests to their selection battery (when it makes sense with established job analyses), as more conscientious employees left the company at slower rates. Also, the company may want to encourage carpooling and reduce barriers to walking to work (e.g., keeping sidewalks clean; providing flexible start times so that employees have ample time to walk to work where applicable; etc.).\n",
    "supporting": [
      "Turnover_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}