{
  "hash": "c1a0489c4e82988b30eab0c4d136696a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Religion and Politics Factorial ANOVA in R\"\neditor: visual\nauthor: Matthew Swanson\ncategories: ['Factorial ANOVA', 'R', 'Religion', 'Constrast Coding', 'phia']\nwarning: FALSE\nmessage: FALSE\n---\n\n\n\n::: text-center\n# **Project Goal**\n:::\n\n![](/images/religpic.jpeg){fig-align=\"center\"}\n\nA client requested to better understand the religious attendance of their constituents and how both their constituent's race and political identity shape religious attendance (with higher scores indicating greater attendance to religious gatherings/events). Additionally, the client specifically requested to compare White, Black, and Hispanic constituents. Thus, the goal of this project was to clean the data and understand how identity shapes religious attendance.\n\nFirst, the data needs to be cleaned:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(dplyr)\n\nData <- subset(Data, PARTYID!= 1 & PARTYID!= 2 & PARTYID!= 3 & PARTYID!= 4 & PARTYID!= 5 & PARTYID!= 9)\nData <- subset(Data, ATTEND!= 9)\nData %>%\nmutate(RACECEN1 = case_when(RACECEN1 == 1 ~ 1,\n                            RACECEN1 ==2 ~ 2,\n                            RACECEN1 ==16 ~ 3,\n                            RACECEN1 ==3 ~ 4,\n                            RACECEN1 ==4 ~ 4,\n                            RACECEN1 == 5 ~ 4,\n                            RACECEN1 ==6 ~ 4,\n                            RACECEN1 ==7 ~ 4,\n                            RACECEN1 ==8 ~ 4,\n                            RACECEN1 ==9 ~ 4,\n                            RACECEN1 == 10 ~ 4,\n                            RACECEN1 ==11 ~ 4,\n                            RACECEN1 ==12 ~ 4,\n                            RACECEN1 ==13 ~ 4,\n                            RACECEN1 ==14 ~ 4,\n                            RACECEN1 ==15 ~ 4,\n                            TRUE ~ 99)) -> Data\n\nData <- subset(Data, RACECEN1!= 99)\nData$PARTYID <- as.factor(Data$PARTYID)\nData$RACECEN1 <- as.factor(Data$RACECEN1)\nData$RACECEN1 <- recode_factor(Data$RACECEN1, '1' = \"White\", '2' = \"Black\", '3' = \"Hispanic\", '4' = \"Other\")\nData$PARTYID <- recode_factor(Data$PARTYID, '0' = \"Democratic\", '6' = \"Republican\", '7' = \"Other\")\nstr(Data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [797 × 3] (S3: tbl_df/tbl/data.frame)\n $ ATTEND  : num [1:797] 6 0 5 3 6 8 5 2 8 0 ...\n $ PARTYID : Factor w/ 3 levels \"Democratic\",\"Republican\",..: 1 2 1 2 1 1 1 1 1 1 ...\n $ RACECEN1: Factor w/ 4 levels \"White\",\"Black\",..: 2 1 2 1 2 3 2 1 1 1 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(Data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  ATTEND PARTYID    RACECEN1\n   <dbl> <fct>      <fct>   \n1      6 Democratic Black   \n2      0 Republican White   \n3      5 Democratic Black   \n4      3 Republican White   \n5      6 Democratic Black   \n6      8 Democratic Hispanic\n```\n\n\n:::\n:::\n\n\n\nThe original \"Religion Data 2\" has several values in each factor that we do not want to look at (either coded as missing or an ambiguous code like \"independent but more democratic\"). I was also asked to look at Black, White, Hispanic individuals as compared to the rest of the participants so I needed to write code that recoded the race variable into something more meaningful (there is originally 16 levels in this variable - some with just single digit cell sizes). I also wanted to assign labels to each level of the factor to aid in clarity.\n\nNow, let's build a two-way ANOVA model and look at the output.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAov <- aov(ATTEND ~ RACECEN1*PARTYID, Data)\nsummary(Aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Df Sum Sq Mean Sq F value   Pr(>F)    \nRACECEN1           3    228   76.12  10.384 1.05e-06 ***\nPARTYID            2    392  195.88  26.721 5.93e-12 ***\nRACECEN1:PARTYID   6     91   15.14   2.066    0.055 .  \nResiduals        785   5754    7.33                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: text-center\n## **Solution 1**\n:::\n\nResults of the two-way ANOVA indicate both a significant main effect for race, F(3,785) = 10.38, p \\<.001, and for political party, F(2,785) = 26.721, p\\<.001, and also a marginally significant interaction, F(6,785) = 2.07, p = .06. For the sake of this client's project, I am going to determine that the marginal p value is close enough to our arbitrary alpha level so I will go ahead and look at the simple effects.\n\nFirst, I want to get the condition means and the cell means.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\n\nCondition_Means <- emmeans(Aov, ~ RACECEN1*PARTYID)\nCondition_Means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n RACECEN1 PARTYID    emmean    SE  df lower.CL upper.CL\n White    Democratic   2.75 0.172 785    2.417     3.09\n Black    Democratic   4.88 0.212 785    4.461     5.29\n Hispanic Democratic   4.59 0.577 785    3.458     5.72\n Other    Democratic   3.44 0.541 785    2.377     4.50\n White    Republican   4.44 0.173 785    4.104     4.78\n Black    Republican   4.83 0.782 785    3.299     6.37\n Hispanic Republican   5.00 1.910 785    1.242     8.76\n Other    Republican   4.44 0.902 785    2.673     6.22\n White    Other        2.60 0.365 785    1.883     3.32\n Black    Other        2.50 0.957 785    0.621     4.38\n Hispanic Other        1.33 1.560 785   -1.735     4.40\n Other    Other        4.50 1.350 785    1.843     7.16\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\nMarginal_MeansRace <- emmeans(Aov, ~ RACECEN1)\nMarginal_MeansRace\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n RACECEN1 emmean    SE  df lower.CL upper.CL\n White      3.27 0.146 785     2.98     3.55\n Black      4.07 0.418 785     3.25     4.89\n Hispanic   3.64 0.846 785     1.98     5.30\n Other      4.13 0.572 785     3.01     5.25\n\nResults are averaged over the levels of: PARTYID \nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\nMarginal_MeansParty <- emmeans(Aov, ~ PARTYID)\nMarginal_MeansParty\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n PARTYID    emmean    SE  df lower.CL upper.CL\n Democratic   3.92 0.209 785     3.50     4.33\n Republican   4.68 0.566 785     3.57     5.79\n Other        2.73 0.577 785     1.60     3.87\n\nResults are averaged over the levels of: RACECEN1 \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n\nYou can also get these means using the dplyr. However, you have to be cautious on the marginal mean calculation which is why I used the emmeans function.\n\nNow that I found a significant interaction, I want to look at the simple effects. In other words, I want to look at the relationship between one predictor on the DV, across all levels of the other predictor. The testinteractions function in the phia package allows me to do this. Note that I have to convert the aov model to a lm model to fit the first argument of this function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(phia)\n\nLM <- lm(ATTEND ~ RACECEN1*PARTYID, Data)\nTest1 <- testInteractions(LM, fixed = \"RACECEN1\", across = \"PARTYID\", adjustment = \"bonferroni\")\nTest1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nF Test: \nP-value adjustment method: bonferroni\n          PARTYID1 PARTYID2    SE1    SE2 Df Sum of Sq       F    Pr(>F)    \n   White    0.1540   1.8431   0.40    0.4  2    401.34 27.3745 1.287e-11 ***\n   Black    2.3773   2.3333   0.98    1.2  2     43.15  2.9430    0.2132    \nHispanic    3.2576   3.6667   1.67    2.5  2     29.20  1.9917    0.5486    \n   Other   -1.0600  -0.0556   1.46    1.6  2      8.93  0.6093    1.0000    \nResiduals                   785.00 5754.5                                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nTest2 <- testInteractions(LM, fixed = \"PARTYID\", across = \"RACECEN1\", adjustment = \"bonferroni\")\nTest2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nF Test: \nP-value adjustment method: bonferroni\n           RACECEN11 RACECEN12 RACECEN13    SE1    SE2     SE3 Df Sum of Sq\nDemocratic  -0.68597   1.43730    1.1509   0.57    0.6 0.79147  3    465.09\nRepublican  -0.00136   0.38889    0.5556   0.92    1.2 2.11655  3      2.32\n     Other  -1.90000  -2.00000   -3.1667   1.40    1.7 2.06789  3     19.20\nResiduals                                785.00 5754.5                     \n                 F    Pr(>F)    \nDemocratic 21.1483 1.052e-12 ***\nRepublican  0.1056         1    \n     Other  0.8733         1    \nResiduals                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nResults indicate that the effect of political party within White individuals is significant, F(2,785) = 27.38, p \\<.001. Results also indicate that the effect of race within Democratic individuals is significant, F(3,785) = 21.15, p \\<.001. Since I found several significant simple effects, I can now follow it up with a simple effects comparison. This is a pairwise comparison of cell means, similar to post-hocs from a one-way ANOVA. I need to break down the multiple degree of freedom effects into single degree of freedom tests so that I know exactly where the difference lies for each effect.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSimple <- testInteractions(LM, pairwise = \"RACECEN1\", fixed = \"PARTYID\", adjustment = \"bonferroni\")\nSimple\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nF Test: \nP-value adjustment method: bonferroni\n                              Value     SE     Df Sum of Sq       F    Pr(>F)\n   White-Black : Democratic -2.1233   0.27    1.0    443.41 60.4882 4.189e-13\nWhite-Hispanic : Democratic -1.8369   0.60    1.0     68.18  9.3011   0.04261\n   White-Other : Democratic -0.6860   0.57    1.0     10.69  1.4578   1.00000\nBlack-Hispanic : Democratic  0.2864   0.61    1.0      1.59  0.2169   1.00000\n   Black-Other : Democratic  1.4373   0.58    1.0     44.78  6.1084   0.24597\nHispanic-Other : Democratic  1.1509   0.79    1.0     15.50  2.1145   1.00000\n   White-Black : Republican -0.3902   0.80    1.0      1.74  0.2377   1.00000\nWhite-Hispanic : Republican -0.5569   1.92    1.0      0.62  0.0839   1.00000\n   White-Other : Republican -0.0014   0.92    1.0      0.00  0.0000   1.00000\nBlack-Hispanic : Republican -0.1667   2.07    1.0      0.05  0.0065   1.00000\n   Black-Other : Republican  0.3889   1.19    1.0      0.78  0.1061   1.00000\nHispanic-Other : Republican  0.5556   2.12    1.0      0.51  0.0689   1.00000\n   White-Black :      Other  0.1000   1.02    1.0      0.07  0.0095   1.00000\nWhite-Hispanic :      Other  1.2667   1.61    1.0      4.56  0.6227   1.00000\n   White-Other :      Other -1.9000   1.40    1.0     13.46  1.8363   1.00000\nBlack-Hispanic :      Other  1.1667   1.83    1.0      2.97  0.4051   1.00000\n   Black-Other :      Other -2.0000   1.66    1.0     10.67  1.4551   1.00000\nHispanic-Other :      Other -3.1667   2.07    1.0     17.19  2.3450   1.00000\nResiduals                           785.00 5754.5                            \n                               \n   White-Black : Democratic ***\nWhite-Hispanic : Democratic *  \n   White-Other : Democratic    \nBlack-Hispanic : Democratic    \n   Black-Other : Democratic    \nHispanic-Other : Democratic    \n   White-Black : Republican    \nWhite-Hispanic : Republican    \n   White-Other : Republican    \nBlack-Hispanic : Republican    \n   Black-Other : Republican    \nHispanic-Other : Republican    \n   White-Black :      Other    \nWhite-Hispanic :      Other    \n   White-Other :      Other    \nBlack-Hispanic :      Other    \n   Black-Other :      Other    \nHispanic-Other :      Other    \nResiduals                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nLooking at the simple effects comparison test output, several results are significant. Specifically, the White-Black difference in religious attendance scores for democrats is significant, F(1, 785) = 60.49, p \\<.001. Since the value is negative, I know that the mean of Black individuals is larger than the mean of White individuals. Sure enough, the mean religious attendance for White democrats (M = 2.75) is significantly smaller than the mean religious attendance for Black democrats (M = 4.88). Additionally, the White-Hispanic difference for religious attendance for democrats is significant, F(1,785) = 9.30, p = .04. The effect is also negative, so I know the mean for Hispanic democrats is larger. Indeed, the mean religious attendance scores for White democrats (M = 2.75) is smaller than the mean religious attendance scores for Hispanic democrats (M = 4.59). I can also look at more pairwise comparisons (the mean of republican Whites vs. Other Hispanics) - but this requires additional codes and considerations.\n\n::: text-center\n## **Solution 2**\n:::\n\nI can also look at interactions by contrast coding for each effect in both main effects and their interactions. This is especially applicable since both main effects and the interaction are significant (while marginal). Since there is a total of 12 groups (3X4 design) I need 11 contrast coded predictors. Race has 4 levels so it needs 3 contrast coded predictors and political party has 3 levels so it needs 2 contrast coded predictors. Then each effect will be crossed, resulting in 5 interaction contrast coded predictors (3 + 2 + 5 = 11). Contrast codes that are assigned to each predictor have to satisfy two conditions to be orthogonal: sum across each group equal zero and the sum of the product of all pairs equal zero ([Data Analysis: A Model Comparison Approach to Regression, ANOVA, and Beyond by Judd, McClelland, & Ryan, 2017](https://sites.google.com/view/dataanalysisbook) provides excellent background on the necessity and development of contrast coding for those curious).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nData%>%\nmutate(x1 = case_when(RACECEN1 ==\"White\" ~ -3,\n                      RACECEN1 ==\"Black\" ~ 1,\n                      RACECEN1 ==\"Hispanic\" ~ 1,\n                      RACECEN1 == \"Other\" ~ 1,\n                      TRUE ~ 99),\nx2 = case_when(RACECEN1 ==\"White\" ~ 0,\n                      RACECEN1 ==\"Black\" ~ -2,\n                      RACECEN1 ==\"Hispanic\" ~ 1,\n                      RACECEN1 == \"Other\" ~ 1,\n                      TRUE ~ 99),\nx3 = case_when(RACECEN1 == \"White\" ~ 0,\n                      RACECEN1 == \"Black\" ~ 0,\n                      RACECEN1 == \"Hispanic\" ~ -1,\n                      RACECEN1 == \"Other\" ~ 1,\n                      TRUE ~ 99),\nx4 = case_when(PARTYID == \"Democratic\" ~ -2,\n                      PARTYID == \"Republican\" ~ 1,\n                      PARTYID == \"Other\" ~ 1,\n                      TRUE ~ 99),\nx5 = case_when(PARTYID == \"Democratic\" ~ 0,\n                      PARTYID == \"Republican\" ~ -1,\n                      PARTYID == \"Other\" ~ 1,\n                      TRUE ~ 99),\nx6 = x1 * x4,\nx7 = x1 * x5,\nx8 = x2 * x4,\nx9 = x2 * x5,\nx10 = x3 * x4,\nx11 = x3 * x5) -> Data\n\nAov2 <- aov(ATTEND ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 + x11, Data)\nsummary(Aov2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value   Pr(>F)    \nx1            1    195  195.24  26.634 3.12e-07 ***\nx2            1     30   29.62   4.041  0.04475 *  \nx3            1      3    3.48   0.475  0.49080    \nx4            1    169  169.40  23.109 1.83e-06 ***\nx5            1    222  222.36  30.333 4.93e-08 ***\nx6            1     53   52.62   7.179  0.00753 ** \nx7            1      0    0.11   0.015  0.90155    \nx8            1      9    8.87   1.209  0.27180    \nx9            1      1    1.38   0.188  0.66474    \nx10           1     16   16.28   2.220  0.13660    \nx11           1     12   11.60   1.582  0.20880    \nResiduals   785   5754    7.33                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nNeed to be clear on what each contrast coded predictor codes for:\n\nx1: difference between White and the average of Black, Hispanic, and other races, across political party\n\nx2: difference between Black and the average of Hispanic and other races, across political party\n\nx3: difference between Hispanic and other races, across political party\n\nx4: difference between democratic and the average of republican and other, across race\n\nx5: difference between republican and other, across race\n\nx6-x11: the interaction of the above contrasts\n\nI won't interpret all effects that are significant, but let's look at a few. x1 codes the difference between White individuals and the average of Black, Hispanic, and other races. This effect is significant, F(1,785) = 26.63, p \\<.001. Since I am comparing White individuals to the average of all other groups across political party, I need to average together some means. The marginal mean for White individuals is 3.27, now we need to get the means for the other racial groups. The average of the other 9 conditions (Black/Hispanic/Other for all 3 political parties) is 3.95 (this is also the mean of the three marginal means of race not including White). So then, x1 is coding the difference between 3.27 and 3.95, which is significant, providing evidence that White individuals attended religious institutions significantly less than the three other racial groups.\n\nx2 codes the difference between democrats and the average of both republicans and others, across race. Looking at marginal means, this effect is coding the difference between a mean of 3.92 for democrats, and a mean of 3.71 for both republicans and others. This effect is significant, suggesting that democrats attended religious institutions significantly more than both republicans and others, F(1,785) = 23.11, p \\<.001.\n\nx6 codes if the difference between White and the average of Black, Hispanic, and other races and for the difference between democrats and the average of republicans and others. The difference for democrats can be found by getting the difference between mean of White dems and the average of the three other racial groups = this difference is -1.55. This value is being compared to a difference between mean of White republican and other and the average of Black, Hispanic, and other individuals in both republic and other groups - this value is -.25. In other words, Whites were less likely to go to religious attendance than the three other racial groups, and this is more true for White democrats, as compared to White republicans and others.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}